//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jorkoh.health.reminders.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Plugin : global::System.Configuration.ApplicationSettingsBase {
        
        private static Plugin defaultInstance = ((Plugin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Plugin())));
        
        public static Plugin Default {
            get {
                return defaultInstance;
            }
        }
    }
}
